question_options = {
    '_birth_year': [2015 - i for i in range(100)],
    'furry_status': {
        'furry': { 'subjective': False },
        'fur_fan': { 'subjective': False },
        'furry_lifestyler': { 'subjective': False },
        'postfurry': { 'subjective': False },
        'furry_adjacent': { 'subjective': False },
        'furry_related': { 'subjective': False },
        'nonfurry': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'clinical_sex': {
        'female': { 'subjective': False },
        'male': { 'subjective': False },
        'intersex': { 'subjective': False },
        'mtf_female': { 'subjective': False },
        'ftm_male': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'gender_identity': {
        'male': { 'subjective': False },
        'mostly_male': { 'subjective': False },
        'both': { 'subjective': False },
        'mostly_female': { 'subjective': False },
        'female': { 'subjective': False },
        'genderqueer': { 'subjective': False },
        'neutrois': { 'subjective': False },
        'nonbinary_nos': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'sexual_orientation': {
        'kinsey_0': { 'subjective': False },
        'kinsey_1': { 'subjective': False },
        'kinsey_2': { 'subjective': False },
        'kinsey_3': { 'subjective': False },
        'kinsey_4': { 'subjective': False },
        'kinsey_5': { 'subjective': False },
        'kinsey_6': { 'subjective': False },
        'pansexual': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'race': {
        'white': { 'subjective': False },
        'black': { 'subjective': False },
        'asian': { 'subjective': False },
        'hispanic': { 'subjective': False },
        'native_american_pacific_islander': { 'subjective': False },
        'middle_eastern': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'spirituality': {
        'christian_catholic': { 'subjective': False },
        'christian_orthodox': { 'subjective': False },
        'christian_protestant': { 'subjective': False },
        'christian_other': { 'subjective': True },
        'muslim': { 'subjective': False },
        'hindu': { 'subjective': False },
        'jewish': { 'subjective': False },
        'pagan': { 'subjective': False },
        'buddhist': { 'subjective': False },
        'atheist': { 'subjective': False },
        'agnostic': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'occupation': {
        'student': { 'subjective': False },
        'administrative': { 'subjective': False },
        'government_armed_service': { 'subjective': False },
        'sales_support': { 'subjective': False },
        'technical_it': { 'subjective': False },
        'professional': { 'subjective': False },
        'service': { 'subjective': False },
        'vet_animal_related': { 'subjective': False },
        'creative_furry': { 'subjective': False },
        'creative_nonfurry': { 'subjective': False },
        'retired': { 'subjective': False },
        'unemployed': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'education': {
        'some_highschool': { 'subjective': False },
        'ongoing_highschool': { 'subjective': False },
        'graduate_highschool': { 'subjective': False },
        'some_university': { 'subjective': False },
        'ongoing_university': { 'subjective': False },
        'graduate_university': { 'subjective': False },
        'ongoing_postcollege': { 'subjective': False },
        'graduate_postcollege': { 'subjective': False },
        'advanced_degree': { 'subjective': False },
        'other': { 'subjective': True },
    },
    'relationship': {
        'single': { 'subjective': False },
        'casual': { 'subjective': False },
        'long_term_committed': { 'subjective': False },
        'legal_non_marriage': { 'subjective': False },
        'married': { 'subjective': False },
    },
    'how_human': {
        'completely_human': { 'subjective': False },
        'completely_human_admire_aspects': { 'subjective': False },
        'mostly_human': { 'subjective': False },
        'both_human_and_other_species': { 'subjective': False },
        'mostly_other_species': { 'subjective': False },
        'other_species': { 'subjective': False },
        'other': { 'subjective': True },
    },
}
